import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { after, test } from 'node:test';
import { Database } from '../src/db.js';
import { raceOpen, raceOpenMixed } from './fixtures/race-barrier.mjs';
import { RACE_MIGRATIONS_V1, RACE_MIGRATIONS_V2 } from './fixtures/migration-race-schema.mjs';

/**
 * Post-production Phase 1: two real, separate OS processes (never in-process instances, never
 * `worker_threads`), barrier-synchronized via `fixtures/race-barrier.mjs` so the race window opens
 * on every run rather than depending on OS scheduling luck, opening the SAME on-disk SQLite file at
 * the same instant against a pending migration. This is the deterministic regression this phase's
 * fix must satisfy — acceptance is these tests passing, not a stress run's failure rate (that is a
 * separate, additional signal — see `migration-race-stress.report.md` generated by
 * `scripts/migration-race-stress.mjs`, not part of the pass/fail suite).
 */

const dirs = /** @type {string[]} */ ([]);
after(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });
function tmp() {
  const d = mkdtempSync(join(tmpdir(), 'migration-race-'));
  dirs.push(d);
  return d;
}

class SeedV1 extends Database {
  static MIGRATIONS = RACE_MIGRATIONS_V1;
}

test('two real processes racing a pending migration on the same file: both succeed, migration applies exactly once, data survives', async () => {
  const dir = tmp();
  const dbPath = join(dir, 'app.db');
  const seed = new SeedV1(dbPath);
  seed.prepare('INSERT INTO users (id, name) VALUES (1, ?)').run('alice');
  seed.close();
  assert.equal(/** @type {any} */ (new DatabaseSync(dbPath).prepare('PRAGMA user_version').get()).user_version, 1, 'sanity: fixture really is at v1 before the race');

  const results = await raceOpen({ dbPath, migrations: RACE_MIGRATIONS_V2, count: 2 });

  for (const r of results) assert.equal(r.ok, true, `both processes must succeed, not crash: ${JSON.stringify(r)}`);
  for (const r of results) assert.equal(r.schemaVersion, 2, `both processes must see the final schema version: ${JSON.stringify(r)}`);

  const final = new DatabaseSync(dbPath);
  assert.equal(/** @type {any} */ (final.prepare('PRAGMA user_version').get()).user_version, 2);
  const migratedCount = /** @type {any} */ (final.prepare('SELECT migrated_count FROM meta WHERE id = 1').get()).migrated_count;
  assert.equal(migratedCount, 1, 'v2\'s non-idempotent UPDATE must have run exactly once — a value of 2 means both racers applied it');
  const rows = /** @type {any[]} */ (final.prepare('SELECT version FROM schema_migrations ORDER BY version').all());
  assert.deepEqual(rows.map((r) => r.version), [1, 2], 'exactly one schema_migrations row per version, no duplicates, no gaps');
  assert.equal(/** @type {any} */ (final.prepare('SELECT name FROM users WHERE id = 1').get()).name, 'alice', 'pre-existing data survived the race untouched');
  final.close();

  // Backup: at least one pre-migration snapshot exists, and every one that does is a valid,
  // independently-openable v1 database (the pre-migration state) — see POST_PRODUCTION_PLAN.md
  // Phase 1 §5 for why this may legitimately be more than one file under a genuine race (VACUUM INTO
  // cannot run inside a transaction, so the backup step itself isn't lock-serialized the way the
  // migration application is; the invariant this asserts is "always at least one, always valid,
  // always pre-migration", not "always exactly one").
  const backups = readdirSync(dir).filter((f) => f.includes('.pre-v1-'));
  assert.ok(backups.length >= 1, `expected at least one pre-migration backup, got: ${JSON.stringify(backups)}`);
  for (const f of backups) {
    const snap = new DatabaseSync(join(dir, f));
    assert.equal(/** @type {any} */ (snap.prepare('PRAGMA user_version').get()).user_version, 1, `${f}: backup must represent the PRE-migration state`);
    assert.equal(/** @type {any} */ (snap.prepare('SELECT name FROM users WHERE id = 1').get()).name, 'alice');
    snap.close();
  }
});

test('two real processes racing to create a fresh/nonexistent database: schema created exactly once, no backup taken', async () => {
  const dir = tmp();
  const dbPath = join(dir, 'app.db'); // never created before this race

  const results = await raceOpen({ dbPath, migrations: RACE_MIGRATIONS_V2, count: 2 });

  for (const r of results) assert.equal(r.ok, true, `both processes must succeed creating a fresh database: ${JSON.stringify(r)}`);
  for (const r of results) assert.equal(r.schemaVersion, 2);

  const final = new DatabaseSync(dbPath);
  assert.equal(/** @type {any} */ (final.prepare('PRAGMA user_version').get()).user_version, 2);
  assert.equal(/** @type {any} */ (final.prepare('SELECT migrated_count FROM meta WHERE id = 1').get()).migrated_count, 1, 'v2 applied exactly once even on a fresh-DB race');
  assert.deepEqual(/** @type {any[]} */ (final.prepare('SELECT version FROM schema_migrations ORDER BY version').all()).map((r) => r.version), [1, 2]);
  final.close();

  assert.equal(readdirSync(dir).filter((f) => f.includes('.pre-v')).length, 0, 'a brand new database is never snapshotted, even under a creation race — nothing existed to protect');
});

test('an older build opening a file already migrated ahead of it refuses (baseline, no race)', async () => {
  const dir = tmp();
  const dbPath = join(dir, 'app.db');
  new SeedV1(dbPath).close();

  const [newerResult] = await raceOpen({ dbPath, migrations: RACE_MIGRATIONS_V2, count: 1 });
  assert.equal(newerResult.ok, true);
  assert.equal(newerResult.schemaVersion, 2);

  const [olderResult] = await raceOpen({ dbPath, migrations: RACE_MIGRATIONS_V1, count: 1 });
  assert.equal(olderResult.ok, false, 'an older build opening a file already at a newer schema must refuse');
  assert.match(olderResult.error ?? '', /newer than this build supports/);
});

test('two processes on different MIGRATIONS lengths racing the same fixture: the shorter one\'s post-lock re-check (not just its unlocked pre-check) correctly rejects a schema the longer one raced ahead to', async () => {
  const dir = tmp();
  const dbPath = join(dir, 'app.db');
  new SeedV1(dbPath).close();

  // Both processes start their Database constructor at the same barrier release: one with the
  // longer MIGRATIONS array (will actually perform the v1->v2 migration), one with the shorter
  // array. At race start, the shorter one's OWN unlocked pre-check still legitimately sees v1 as
  // within its own supported range (current === migrations.length for its own 1-migration view) —
  // this exercises whether its POST-LOCK fresh re-read also correctly discovers, once the longer
  // process has won and committed the v1->v2 migration, that the file ended up newer than it
  // supports.
  const [newerOutcome, olderOutcome] = await raceOpenMixed({ dbPath, migrationsPerChild: [RACE_MIGRATIONS_V2, RACE_MIGRATIONS_V1] });
  assert.equal(newerOutcome.ok, true, `the longer-MIGRATIONS process must succeed: ${JSON.stringify(newerOutcome)}`);
  assert.equal(newerOutcome.schemaVersion, 2);
  // The shorter-MIGRATIONS process either wins the lock first (sees v1, already "current" for its
  // own 1-migration view — succeeds, reports schemaVersion 1) or loses the lock to the longer one
  // and, on its own post-lock fresh re-read, finds the file at v2 while it only supports v1 —
  // refuses. Both are correct outcomes for a mixed-version race; what must NEVER happen is the
  // shorter process silently reporting success at v2 (a version it cannot account for) or crashing
  // with anything other than the documented ConfigError message.
  if (olderOutcome.ok) {
    assert.equal(olderOutcome.schemaVersion, 1, 'the shorter-MIGRATIONS process must never report a schemaVersion it cannot account for');
  } else {
    assert.match(olderOutcome.error ?? '', /newer than this build supports/, `the shorter-MIGRATIONS process's failure must be the documented forward-version refusal, not something else: ${JSON.stringify(olderOutcome)}`);
  }
});
